### ISSUE TITLE
Unable to run Medusa with Python3

### ISSUE THREAD

**Issue by IgorGanapolsky** [Ch0pin/medusa#14]
Hello,
I am trying to run `python3 medusa.py`, and get this error:
> Traceback (most recent call last):
  File "/Users/myuser/workspace/git/Ch0pin/medusa/medusa.py", line 4, in <module>
    import cmd2
ModuleNotFoundError: No module named 'cmd2'

Any solution?

**Comment by Ch0pin** [comment]
pip install cmd2

**Comment by wb4r** [comment]
The suggested solution doesn't work

`$ pip3 install cmd2                              ░▒▓ 127 ✘ 
Requirement already satisfied: cmd2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: wcwidth>=0.1.7 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from cmd2) (0.2.5)
Requirement already satisfied: attrs>=16.3.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from cmd2) (22.1.0)
Requirement already satisfied: pyperclip>=1.6 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from cmd2) (1.8.2)
WARNING: You are using pip version 20.2.3; however, version 22.2.2 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -m pip install --upgrade pip' command.

$ python3 mango.py                                   ░▒▓ ✔ 
Traceback (most recent call last):
 File "/Users/wtoledano/apps/medusa/mango.py", line 5, in <module>
   from libraries.libmango import *
 File "/Users/wtoledano/apps/medusa/libraries/libmango.py", line 3, in <module>
   import cmd2, os, sys, platform,requests
ModuleNotFoundError: No module named 'cmd2'`

**Comment by Ch0pin** [comment]
sure you can install using virtual environment, although the 1st issue had to do with which python you are using. Apparently the install site doesn't correspond to the actual python used.
