### ISSUE TITLE
No availlable info

### ISSUE THREAD

**Issue by jiahaoabc** [Ch0pin/medusa#15]
hello, no matter which apk i run, it shows “ No availlable info”。

**Comment by Ch0pin** [comment]
Can you be more specific , type exactly the command you are issuing ?

**Comment by jiahaoabc** [comment]
> 你能更具体一点，准确输入你发出的命令吗？

**Comment by jiahaoabc** [comment]
Thanks for your reply, whenever I execute “run -f package_name”，it shows “ No availlable info”

**Comment by jiahaoabc** [comment]
`medusa> run -f com.zhiliaoapp.musically

com.zhiliaoapp.musically

Spawned package : com.zhiliaoapp.musically on pid 25249

[in-session] |e:exit |r:reload | i:info | ?:help |:i

[!] No availlable info.
`

**Comment by Ch0pin** [comment]
got it, did you try another app ? does it do the same ?

**Comment by jiahaoabc** [comment]
Yes, every app I try has the same result

**Comment by Ch0pin** [comment]
Frida and frida server version ?

**Comment by jiahaoabc** [comment]
Frida:15.1.13
frida server:frida-server-15.1.13-android-arm64

**Comment by Ch0pin** [comment]
Thank you @jiahaoabc , the application-info-data source originates from a frida script which is embedded in the agent.js. Although that I am not able to replicate it my set up, I'll check if there are any conditions that might trigger this behaviour. 
Do you have issues with other scripts also ? 

For example if you use the webviews/hook_webviews or ipc/ipc , do you get any errors ?

**Comment by jiahaoabc** [comment]
Thanks, I'll check it out
