### ISSUE TITLE
Gitflow workflow

### ISSUE THREAD

**Issue by saraivamarco** [Ch0pin/medusa#2]
Hi,

I would like to contribute to this repository, and I believe that others would like to do that as well.

My suggestion is to create a Gitflow workflow, which creates a workflow branching (creates a few more branches like **develop**) to enable others to contribute without messing arond with the **master** branch. More details on - [https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow](url)

### Intallation for MacOs
```brew install git-flow```

### Initialization of the Git workflow
```git flow init```

### Usage
Switch to the **develop** branch

```git checkout develop```

Do whatever changes you need to do, and perform a push to the repo.

```git push -u origin develop```

_Note: Don't forget to pull any changes before making your own._

You'll notice that all changes are made in the **develop** branch, but the **master** will remain untouched (unless you want to merge the changes).

**Comment by Ch0pin** [comment]
A develop branch has been initialised
