### ISSUE TITLE
Bypassing Unity pinning possible?

### ISSUE THREAD

**Issue by yoshimo** [Ch0pin/medusa#20]
Unity based applications have their own additional certificate checks like described for example in https://docs.unity3d.com/ScriptReference/Networking.CertificateHandler.ValidateCertificate.html

Your various unpinning modules are nice, but the universal and the specific ones both don't cover the Unity methods yet.
Would be nice if you could extend your toolset.

**Comment by Ch0pin** [comment]
Do you have a show case app ?

**Comment by yoshimo** [comment]
Niantics Ingress, Blizzards Hearthstone Trading Card Game

**Comment by yoshimo** [comment]
https://play.google.com/store/apps/details?id=com.micropets.runner

**Comment by yoshimo** [comment]
```https://play.google.com/store/apps/details?id=se.maginteractive.quizduel2```
too

**Comment by TheDauntless** [comment]
Blizzards Hearthstone Trading Card Game doesn't use SSL pinning and neither does quizduel2. I couldn't install the micropetsrunner game to check.

The checks you mentioned are optional and don't seem to be implemented in these games.

**Comment by yoshimo** [comment]
@TheDauntless  how did you get anything out of these applications other than firebase logging?
I stand by my initial claim, these apps do not trust the android cert store with manually added system&user certificates.

**Comment by TheDauntless** [comment]
@yoshimo  Just booted the app again. This is the quiz app:

<img width="1127" alt="image" src="https://github.com/Ch0pin/medusa/assets/1650034/2ee0a0af-f3ee-4b7a-9b6e-36856987ba10">

Yes, the payloads are encrypted, but that has nothing to do with SSL pinning.

For heartstone, there are requests to `telemetry-in.battle.net` and `txql0v-inapps.appsflyersdk.com` and a few that don't listen to proxy settings (`api.blizzard.com` and `cdn.blz-contentstack.com`). I don't know which data you're after specifically, but I haven't received any error related to TLS pinning on any of the Unity apps proposed in this thread.
<img width="1125" alt="image" src="https://github.com/Ch0pin/medusa/assets/1650034/74091451-7acf-4d00-bda2-b9349b236459">

If you're having trouble MITM'ing, maybe try following [my checklist.](https://blog.nviso.eu/2020/11/19/proxying-android-app-traffic-common-issues-checklist/)
