### ISSUE TITLE
Cannot see strace log

### ISSUE THREAD

**Issue by a2t2** [Ch0pin/medusa#25]
I am new to medusa. I wanted to test the strace feature. I tried to run strace as follows:

```
medusa> strace com.example.myapp
Spawned package : com.example.myapp on pid 21251
----- Credits @FrenchYeti -----
[i] Type 'e' to exit the strace 
Type 'e' to exit:e

medusa>
```

Running the strace command launches the app. After interacting with the app for a while, I don't see any log in the terminal. How can I see the strace log ? Thanks.

**Comment by Ch0pin** [comment]
do you use an emulator ?

**Comment by a2t2** [comment]
No I am using a real Android device.

**Comment by Ch0pin** [comment]
I checked the script today and works fine in my device, this is why I am asking.
