### ISSUE TITLE
Cannot see file download operation when testing with browser

### ISSUE THREAD

**Issue by a2t2** [Ch0pin/medusa#26]
I am testing the modules under the file_system category. The scenario I am trying to test is to see whether the medusa modules can log a PDF file download operation done by a browser. I tested a browser using the following modules:

```
medusa> use file_system/file_write 

Current Mods:
0) file_system/get_catch_directory
1) file_system/input_output
2) file_system/file_write
```
If I test with all file_system modules, the browser crashes on launch, so I picked the above three. After launching the browser (using run -f), I can see file writes logged by medusa, but cannot see any log for the PDF download operation. I suspect the browser may have forked a process to do the download. Any suggestions on how to use file_system modules if some operation may happen in a forked process ?

**Comment by Ch0pin** [comment]
The file_write would be enough I guess. Check if it drops the file with some temporary name or something.
