### ISSUE TITLE
Can't Install on macOS 12.6.1

### ISSUE THREAD

**Issue by QueTheWizard** [Ch0pin/medusa#33]
Tried to install it with a few different python versions (3.10, 3.11, 3.9, 3.8) all of them returned the same error initially:
<img width="1440" alt="2022-11-18_09-43-06" src="https://user-images.githubusercontent.com/20052885/202648270-cd106310-268d-4f0d-a632-d7f544af651c.png">
Afterwards I changed the readline version to 6.2.4.1 and it couldn't install it, with the following error:
<img width="1440" alt="2022-11-18_09-47-06" src="https://user-images.githubusercontent.com/20052885/202648861-d6414417-5185-4b4e-81ab-1fe316e43e4e.png">

**Comment by Ch0pin** [comment]
can you remove the readline from the requirements and try again ?

**Comment by QueTheWizard** [comment]
@Ch0pin Thanks, worked for mango.py, but medusa.py needed additional dependency - google_trans_new
Installed and it worked
<img width="1440" alt="2022-11-18_11-58-28" src="https://user-images.githubusercontent.com/20052885/202674947-355365d6-dd9a-4508-b875-3ef9b532e056.png">

**Comment by Ch0pin** [comment]
google_trans_new has a small issue, I have some directions on how to use it in the README
