### ISSUE TITLE
[bug] invalid redefinition of a variable

### ISSUE THREAD

**Issue by Iscle** [Ch0pin/medusa#37]
Greetings!

While using medusa I encountered an error which prevented me from using a mod combination I wanted.

The error is: 
```
script(line 1250): SyntaxError: invalid redefinition of a variable
```

I was using the following mods at the time:
```
Current Mods:
0) helpers/anti_debug
1) JNICalls/FindClass
2) code_loading/native_libs
3) code_loading/dump_dex
```

I cloned at commit 676cbb8.

Regards,
Iscle

**Comment by Ch0pin** [comment]
Hi, thanks for reporting this. 

Must be fixed now, feel free to reopen in case it is not.
