### ISSUE TITLE
Readline module not supported for android

### ISSUE THREAD

**Issue by vikramn99** [Ch0pin/medusa#4]
Hi, When i am trying to use medusa in windows 10, I am getting error.
Error:
Readline module not supported, so please consider this issue, and give us alternative option for this.

Many of users are using windows OS, if this issue is solved, it would be great for us to do pentest :)

**Comment by Ch0pin** [comment]
Thanks for reporting that @vikramn99 , I'll take it under consideration for the next updates.

**Comment by Ch0pin** [comment]
https://copdips.com/2018/05/using-readline-in-python-repl-on-windows.html

**Comment by vikramn99** [comment]
Hi, I am also tried with pyreadline in windows, but still i am unable to run medusa.

what i done :
`import pyreadline as redline`

This are the error logs:
`Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\MobileTools\medusa-master\medusa.py", line 6, in <module>
    from libraries.defs import *
  File "C:\Users\Administrator\Desktop\MobileTools\medusa-master\libraries\defs.py", line 17, in <module>
    if 'libedit' in readline.__doc__:
TypeError: argument of type 'NoneType' is not iterable`

Please look out this issue.
