### ISSUE TITLE
How can I get all the packages (not only third part, also system app)

### ISSUE THREAD

**Issue by Securee** [Ch0pin/medusa#42]
ubuntu 20.04
Python 3.8.10
first,I use the list command to see all package in my phone:
![image](https://github.com/Ch0pin/medusa/assets/79675350/4a395f78-4241-409f-b511-830e9fc8c5b6)
       the list command only showe third part packages, how can I get all the packages in the phone, including system app, platform app ?

**Comment by Ch0pin** [comment]
Hi @Securee , currently you can't, but thank you for pointing that out. I'll add it in one of the next updates.

**Comment by Securee** [comment]
> Hi @Securee , currently you can't, but thank you for pointing that out. I'll add it in one of the next updates.
Great! Glad to hear it.

**Comment by Ch0pin** [comment]
Done . Thanks again.
