### ISSUE TITLE
How do I hook child process?

### ISSUE THREAD

**Issue by luedong776** [Ch0pin/medusa#47]
It seems that `run` and `run -f `cannot hook the subprocess of an application.

**Comment by Ch0pin** [comment]
noted , I'll add support in one of the next updates . Thanks !

**Comment by Ch0pin** [comment]
@luedong776,  added an option to hook by process id:

>run -p 

or 

>run -p 1234

 let me know if it works.

**Comment by luedong776** [comment]
Yes, it works.
