### ISSUE TITLE
Add support for networked host

### ISSUE THREAD

**Issue by slothhy** [Ch0pin/medusa#63]
Due to certain apps detecting the frida default port, is it possible to add support for devices running frida on a different port? 

https://github.com/frida/frida/issues/70#issuecomment-522453301

**Comment by Ch0pin** [comment]
@slothhy , accepted. 

It will be added shortly !

**Comment by Ch0pin** [comment]
feature added in https://github.com/Ch0pin/medusa/commit/e6c7c402fb93504f6e2a31f94888c616a22a0f3b

You can use the the run command as normally adding the --host IP:PORT parameter
