### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Ch3nYe** [Ch0pin/medusa#7]
`modules/cordova/cordova_enable_debugging.med` miss '}'

**Comment by Ch3nYe** [comment]
> `modules/cordova/cordova_enable_debugging.med` miss '}'

I don't know is there something like pull request rule that fix this tiny bug couldn't lanch a pr? If not I could send pr to fix these tiny bug.

**Comment by Ch0pin** [comment]
Thanks @Ch3nYe , 

Noted and it is going to be fixed on the next push.
