### ISSUE TITLE
Unreachable Medusa Agent URL

### ISSUE THREAD

**Issue by dipa96** [Ch0pin/medusa#71]
When trying the `InstallBurpCert` feature with `mango`, the URL address that makes it possible to download the Medusa agent appears to be unreachable.

Log:
```
mango➤installagent
[?] Medusa Agent has not been downloaded, do you want to do it now ? (Y/n) Y
2024-01-03 23:01:04,638 - DEBUG - connectionpool.py:1019 -> _new_conn : Starting new HTTPS connection (1): github.com:443
2024-01-03 23:01:05,250 - DEBUG - connectionpool.py:474 -> _make_request : https://github.com:443 "GET /Ch0pin/mango/raw/main/agent.apk HTTP/1.1" 404 None
```

File: `libraries/libmango.py`
String: `MEDUSA_AGENT_URL = "https://github.com/Ch0pin/mango/raw/main/agent.apk"`

**Comment by Ch0pin** [comment]
Hi @dipa96 , thanks for reporting this. The idea is to deprecate the agent in future releases, so the `InstallBurpCert` will work without using the agent. I am working on it, and this issue will be resolved shortly.

**Comment by Ch0pin** [comment]
Fixed in https://github.com/Ch0pin/medusa/commit/856fd6dee2c0c453fba66b2475e87a13f142ceb0 

Please note that for Android 11 or higher you have to perform an extra step and navigate to the android settings in order to install the certificate manually.
