### ISSUE TITLE
helpers/translator does not use utils.google_trans_new

### ISSUE THREAD

**Issue by alright21** [Ch0pin/medusa#78]
I noticed that translator module does not load the local library `utils.google_trans_new`, but uses instead the one downloaded from requirements.txt. 
I was having some issues in loading this module because it was using `.cn` domain instead `.com` (I don't know why but the library downloaded uses this suffix as default).
Two solutions:
- use `utils.google_trans_new` and remove the dependency
- intatiate `translator = google_translator(url_suffix='com')`

I can work on it, based on the preferred solution.

**Comment by Ch0pin** [comment]
Hi @alright21 , 

 I think it is better to use the one in the utils folder.

**Comment by alright21** [comment]
Ok sure, should I also remove the dependency from `requirements.txt`?

**Comment by Ch0pin** [comment]
I can't see it used somewhere else, so it is fine I guess
