### ISSUE TITLE
Issue while using modules - invalid redefinition of a variable

### ISSUE THREAD

**Issue by Somberor** [Ch0pin/medusa#81]
If I use any module and compile. when trying to run the app (i.e com.instagram.android)
I will get the error
invalid redefinition of a variable

medusa➤run -f com.instagram.android
Spawned package : com.instagram.android on pid 4754
script(line 6656): SyntaxError: invalid redefinition of a variable

in the past it used to work and I don't recall changing anything, also tried recloning Medusa, but nothing helps
any suggestions?

**Comment by Ch0pin** [comment]
can you give me the list of modules you are using ?

**Comment by Somberor** [comment]
only instagram ssl unpinning

**Comment by Ch0pin** [comment]
Doesn't make much sense, using just the instagram ssl unpinning module, yields something like 800 lines to the final script. Having such an error in line 6656, implies that you have additional modules, or for some reason the final script hasn't been reset. 

This error normally means that variables which are defined in two modules are conflicting. So, I suggest to reset the script and then re import the modules. You can do that by typing:

```
medusa> reset
````
and then 

````
medusa> use http_communications/instagram_ssl_pinning_bypass
````
 
If it doesn't get resolved, it would help to add here what is in line 6656 of the `medusa/agent.js` file
