### ISSUE TITLE
unable to find process with name 'system_server'

### ISSUE THREAD

**Issue by cryptax** [Ch0pin/medusa#87]
Why do I get this error when trying to load this malware?

```
medusa>run -n 0
An error occurred: unable to find process with name 'system_server'
```

It's a sample of Android/Ermac: `e578094837ef57de94414604d6a39a7966929dc04a693f20244db66fecdfdc98`.

Setup: Linux, Android 13 emulator with malware installed, latest medusa from git.

**Comment by Ch0pin** [comment]
@cryptax ,  try to run  `medusa>list -3` first
