### ISSUE TITLE
Virtual Device (Genymobile), No Response issue

### ISSUE THREAD

**Issue by mali44** [Ch0pin/medusa#9]
I have successfully had the framework in my computer. Medusa could see the device and list the installed packages. So far so good. After any run attempt the shell hangs  in idle for so long without any response. 

To what I understood by looking at the results, the application can not be spawned by the medusa over the frida and agent... no idea why. 

(I was able to spawn for checking frida, its working fine, manually able to spawn it with the frida inside medusa virtual)

Is there any solution/suggestion for virtual phone devices ? 

![image](https://user-images.githubusercontent.com/16443213/138564404-ee41629d-82c0-47bc-b2a7-e0237f32175c.png)

**Comment by Ch0pin** [comment]
it is  probably an incompatibility between the server and client of your frida installation. Make sure you have the same versions installed.
